export const SEARCH_FILM= 'SEARCH_FILM';
export const FETCH_NEW_FILM_SUCCESS= 'FETCH_NEW_FILM_SUCCESS';
export const FETCH_NEW_FILM_ERROR= 'FETCH_NEW_FILM_ERROR';
export const GET_FILM= 'GET_FILM';
export const GET_FILM_ERROR= 'GET_FILM_ERROR';
